#!/usr/bin/env python3
#
# Copyright 2012 Lee Verberne <lee@blarg.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import logging
import os
import shlex
import subprocess
import sys

VERSION='0.1'

class CfGitRepository(object):
    '''A Git repository used for storing configuration files

    This class represents a git respository that is used to control
    configuration files and provides a set of actions useful for automating
    common tasks.

    Note: This object will run system commands, alter the environment and
    change directories.  Beware.
    '''
    def __init__(self, repopath=None):
        'Initialize the environment for running git commands'
        self.log = logging.getLogger('CfGitRepository')
        if repopath:
            os.chdir(repopath)

        # Gather ye info
        self.initial_head = self._git('describe --always').strip()
        self.log.debug('Setting initial_head to %s', self.initial_head)
        self._gather_sync_config()

    def _gather_sync_config(self):
        '''Read cfsync configuration for this repository

        cfsync configuration is stored via 'git-config', which makes it easy
        link configuration to particular repositories.  This procedure reads
        all known configuration values into self.config.
        '''
        config = {}
        for key in ('fetch', 'merge', 'options', 'pull', 'reload'):
            try:
                config[key] = self._git('config --get-all cfsync.' + key)\
                                  .strip('\n').split('\n')
                self.log.debug('setting %s config to: %s', key, repr(config[key]))
            except subprocess.CalledProcessError:
                config[key] = []

        self.config = config

    def _git(self, cmdstr):
        cmd = ['git',] + shlex.split(cmdstr)
        self.log.debug("Running git command: %s", repr(cmd))
        return subprocess.check_output(cmd, universal_newlines=True)

    def _run_git_generic(self, subcmd_str):
        'Run a git command in a completely not-special way'
        for subcmd_target in self.config[subcmd_str]:
            self._git(subcmd_str + ' ' + subcmd_target)

    def _run_reload(self):
        'Do something if this repository has changed'
        for reload_command in self.config['reload']:
            self.log.info("Running reload command: %s", reload_command)
            try:
                subprocess.check_call(reload_command, shell=True,
                                      universal_newlines=True)
            except subprocess.CalledProcessError as e:
                logging.error("Reload command failed, aborting immediately.")
                raise e

    def run_periodic_tasks(self):
        'Perform tasks that should run periodically'
        # Run git commands
        for command in ('fetch', 'pull', 'merge'):
            if self.config[command]:
                self._run_git_generic(command)

        # Conditionally do things based on what happened
        cur_head = self._git('describe --always').strip()
        if (cur_head != self.initial_head or 
            'always_reload' in self.config['options']):
            self.log.info("Repository state has changed (%s -> %s)",
                          self.initial_head, cur_head)
            self._run_reload()

def parse_arguments():
    'Parse arguments from command line invocation'
    parser = argparse.ArgumentParser(prog='git-cfsync')
    parser.add_argument('repopath', metavar='PATH', nargs='?',
                        help="path to git repository")
    parser.add_argument('-d', '--debug', action='store_const',
                        const=logging.DEBUG, dest='loglevel',
                        help="Enable debug messages")
    parser.add_argument('-v', '--verbose', action='store_const',
                        const=logging.INFO, dest='loglevel',
                        help="Enable verbose logging")
    parser.add_argument('-V', '--version', action='version', version=VERSION)
    return parser.parse_args()

def main():
    args = parse_arguments()
    if args.loglevel:
        logging.getLogger().setLevel(args.loglevel)
        logging.debug("Set logging level")

    try:
        cfgit = CfGitRepository(args.repopath)
        cfgit.run_periodic_tasks()
    except Exception as e:
        if args.loglevel == logging.DEBUG:
            raise e
        else:
            print('Error:', e, file=sys.stderr)

if __name__ == "__main__":
    main()
